policy:
  control_frequency: 50.0
  default_joint_angles:
    FL_hip_joint: 0.1
    RL_hip_joint: 0.1
    FR_hip_joint: -0.1
    RR_hip_joint: -0.1
    FL_thigh_joint: 0.8
    RL_thigh_joint: 0.8
    FR_thigh_joint: 0.8
    RR_thigh_joint: 0.8
    FL_calf_joint: -1.5
    RL_calf_joint: -1.5
    FR_calf_joint: -1.5
    RR_calf_joint: -1.5
  num_actions: 12
  num_commands: 3
  num_policy_observations: 119
  num_estimator_observations: 116
  num_privileged_observations: 10
  active_policy_observation_components:
    - [commands, 3]
    - [projected_gravity, 3]
    - [dof_positions, 12]
    - [dof_velocities, 12]
    - [last_actions, 12]
    - [height_measurements, 77]
  active_estimator_observation_components:
    - [projected_gravity, 3]
    - [dof_positions, 12]
    - [dof_velocities, 12]
    - [last_actions, 12]
    - [height_measurements, 77]
  active_privileged_observation_components:
    - [friction, 1]
    - [restitution, 1]
    - [body_velocity, 3]
    - [contact_states, 4]
    - [height_measurements_z_bias, 1]
  sparse_policy_obs_history: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  sparse_estimator_obs_history: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  obs_scales:
    linear_vel: 2.0
    angular_vel: 0.25
    projected_gravity: 1.0
    dof_positions: 1.0
    dof_velocities: 0.05
    height_measurements: 5.0
    body_height_cmd: 2.0
    gait_phase_cmd: 1.0
    gait_freq_cmd: 1.0
    footswing_height_cmd: 0.15
    body_pitch_cmd: 0.3
    body_roll_cmd: 0.3
    aux_reward_cmd: 1.0
    compliance_cmd: 1.0
    stance_width_cmd: 1.0
    stance_length_cmd: 1.0
  obs_bias:
    height_measurements: 0.3
  action_scale: 0.25
  hip_scale_reduction: 1.0
  clip_actions: 20.0
  clip_observations: 100.0
  normalization_ranges:
    friction_range: [-0.5, 6.0]
    ground_friction_range: [0.05, 4.5]
    restitution_range: [0, 0.4]
    added_mass_range: [-1.0, 3.0]
    com_displacement_range: [-0.1, 0.1]
    motor_strength_range: [0.9, 1.1]
    motor_offset_range: [-0.05, 0.05]
    Kp_factor_range: [0.8, 1.3]
    Kd_factor_range: [0.5, 1.5]
    joint_friction_range: [0.0, 0.7]
    contact_force_range: [0.0, 50.0]
    contact_state_range: [0.0, 1.0]
    body_velocity_range: [-6.0, 6.0]
    x_velocity_range: [-2, 2]
    y_velocity_range: [-1, 1]
    z_velocity_range: [-1, 1]
    pitch_velocity_range: [-2.0, 2.0]
    roll_velocity_range: [-2.0, 2.0]
    yaw_velocity_range: [-2.0, 2.0]
    foot_height_range: [0.02, 0.08]
    body_height_range: [0.0, 0.6]
    gravity_range: [-1.0, 1.0]
    height_measurements_bias_range: [-0.1, 0.1]
    height_measurements_z_bias_range: [-0.05, 0.05]
  pacing_offset: false
  terrain:
    measure_heights: true
    measured_points_x: [-0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
    measured_points_y: [-0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3]
  command_limits:
    body_height: [0.0, 0.0]
    step_frequency: [0.0, 0.0]
    gait_phase: [0.0, 0.0]
    gait_offset: [0.0, 0.0]
    gait_bound: [0.0, 0.0]
    gait_duration: [0.0, 0.0]
    footswing_height: [0.0, 0.0]
    body_pitch: [0.0, 0.0]
    body_roll: [0.0, 0.0]
    stance_width: [0.0, 0.0]
    stance_length: [0.0, 0.0]
  control:
    control_type: P
    kp_gain: 25.0
    kd_gain: 0.5
